package dev.obscuria.elixirum.server.alchemy.generation;

import dev.obscuria.elixirum.ArsElixirum;
import dev.obscuria.elixirum.common.alchemy.basics.Essence;
import dev.obscuria.elixirum.config.GenerationSettings;
import dev.obscuria.elixirum.server.alchemy.generation.operations.Operation;
import dev.obscuria.elixirum.server.alchemy.generation.operations.ProposeOperation;
import dev.obscuria.elixirum.server.alchemy.generation.operations.RejectOperation;
import dev.obscuria.elixirum.server.alchemy.resources.PredefinedEssence;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.effect.MobEffect;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

public interface EssenceGenerationPipeline {

    List<GenerationStep<Holder.Reference<MobEffect>, Essence>> STEPS = List.of(
            EssenceGenerationPipeline::rejectIfBlacklisted,
            EssenceGenerationPipeline::proposePredefined,
            EssenceGenerationPipeline::rejectIfNotWhitelisted,
            EssenceGenerationPipeline::proposeAutogenerated);

    static Map<Holder.Reference<MobEffect>, Operation<Essence>> generate() {
        return BuiltInRegistries.MOB_EFFECT.holders().collect(Collectors.toMap(
                Function.identity(), effect -> {
                    for (var generationStep : STEPS) {
                        var operation = generationStep.apply(effect);
                        if (operation.isEmpty()) continue;
                        return operation.get();
                    }
                    return new RejectOperation<>();
                }));
    }

    private static Optional<Operation<Essence>> rejectIfBlacklisted(Holder.Reference<MobEffect> effect) {
        return isBlacklisted(effect)
                ? Optional.of(new RejectOperation<>())
                : Optional.empty();
    }

    private static Optional<Operation<Essence>> proposePredefined(Holder.Reference<MobEffect> effect) {
        return PredefinedEssence.findFor(effect)
                .map(Holder.Reference::value)
                .map(PredefinedEssence::essence)
                .map(ProposeOperation::new);
    }

    private static Optional<Operation<Essence>> rejectIfNotWhitelisted(Holder.Reference<MobEffect> effect) {
        return !isWhitelisted(effect)
                ? Optional.of(new RejectOperation<>())
                : Optional.empty();
    }

    private static Optional<Operation<Essence>> proposeAutogenerated(Holder.Reference<MobEffect> effect) {
        return new EssenceGenerator()
                .generateEssence(effect)
                .map(ProposeOperation::new);
    }

    private static boolean isBlacklisted(Holder.Reference<MobEffect> effect) {
        if (!GenerationSettings.ESSENCE_BLACKLIST_ENABLED.get()) return false;
        if (effect.is(ArsElixirum.IGNORED_EFFECTS)) return true;
        if (GenerationSettings.ESSENCE_BLACKLIST.has(effect.value())) return true;
        return false;
    }

    private static boolean isWhitelisted(Holder.Reference<MobEffect> effect) {
        if (!GenerationSettings.ESSENCE_WHITELIST_ENABLED.get()) return true;
        if (effect.is(ArsElixirum.ALLOWED_EFFECTS)) return true;
        if (GenerationSettings.ESSENCE_WHITELIST.has(effect.value())) return true;
        return false;
    }
}