package dev.obscuria.elixirum.server.alchemy.generation;

import dev.obscuria.elixirum.ArsElixirum;
import dev.obscuria.elixirum.common.alchemy.basics.Essence;
import dev.obscuria.elixirum.config.GenerationSettings;
import dev.obscuria.elixirum.server.alchemy.generation.operations.Operation;
import dev.obscuria.elixirum.server.alchemy.generation.operations.ProposeOperation;
import dev.obscuria.elixirum.server.alchemy.generation.operations.RejectOperation;
import dev.obscuria.elixirum.server.alchemy.resources.PredefinedEssence;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.effect.MobEffect;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public final class EssenceGenerationPipeline {

    private static final List<GenerationStep<Holder.Reference<MobEffect>, Essence>> STEPS = List.of(
            EssenceGenerationPipeline::rejectIfBlacklisted,
            EssenceGenerationPipeline::proposePredefined,
            EssenceGenerationPipeline::rejectIfNotWhitelisted,
            EssenceGenerationPipeline::proposeAutogenerated);

    public static Map<Holder.Reference<MobEffect>, Operation<Essence>> generate() {
        return streamEffectHolders().collect(Collectors.toMap(
                Function.identity(),
                EssenceGenerationPipeline::applySteps));
    }

    private static Stream<Holder.Reference<MobEffect>> streamEffectHolders() {
        return BuiltInRegistries.MOB_EFFECT.holders()
                .collect(Collectors.toMap(
                        Holder.Reference::key,
                        Function.identity(),
                        EssenceGenerationPipeline::logAndKeepFirst))
                .values().stream();
    }

    private static Operation<Essence> applySteps(Holder.Reference<MobEffect> effect) {
        return STEPS.stream()
                .map(step -> step.apply(effect))
                .filter(Optional::isPresent)
                .map(Optional::get)
                .findFirst()
                .orElseGet(RejectOperation::new);
    }

    private static <T> T logAndKeepFirst(T first, T duplicate) {
        ArsElixirum.LOGGER.warn("Duplicate MobEffect holder detected, skipping: {}", duplicate);
        return first;
    }

    private static boolean isBlacklisted(Holder.Reference<MobEffect> effect) {
        if (!GenerationSettings.ESSENCE_BLACKLIST_ENABLED.get()) return false;
        if (effect.is(ArsElixirum.IGNORED_EFFECTS)) return true;
        if (GenerationSettings.ESSENCE_BLACKLIST.has(effect.value())) return true;
        return false;
    }

    private static boolean isWhitelisted(Holder.Reference<MobEffect> effect) {
        if (!GenerationSettings.ESSENCE_WHITELIST_ENABLED.get()) return true;
        if (effect.is(ArsElixirum.ALLOWED_EFFECTS)) return true;
        if (GenerationSettings.ESSENCE_WHITELIST.has(effect.value())) return true;
        return false;
    }

    private static Optional<Operation<Essence>> rejectIfBlacklisted(Holder.Reference<MobEffect> effect) {
        return isBlacklisted(effect)
                ? Optional.of(new RejectOperation<>())
                : Optional.empty();
    }

    private static Optional<Operation<Essence>> proposePredefined(Holder.Reference<MobEffect> effect) {
        return PredefinedEssence.findFor(effect)
                .map(Holder.Reference::value)
                .map(PredefinedEssence::essence)
                .map(ProposeOperation::new);
    }

    private static Optional<Operation<Essence>> rejectIfNotWhitelisted(Holder.Reference<MobEffect> effect) {
        return !isWhitelisted(effect)
                ? Optional.of(new RejectOperation<>())
                : Optional.empty();
    }

    private static Optional<Operation<Essence>> proposeAutogenerated(Holder.Reference<MobEffect> effect) {
        return new EssenceGenerator()
                .generateEssence(effect)
                .map(ProposeOperation::new);
    }
}